name: GDAL Windows Build
# This workflow will build the wxWidgets library for Windows using CMake and Conan

#on:
#  release:
#    types: [created]

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # runs-on: macos-15
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python "3.12"
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Conan
      run: |
        python -m pip install --upgrade pip
        pip install wheel conan==1.*

    - name: Install Conan Libraries
      shell: bash
      #working-directory: ${{github.workspace}}/build
      run: |
        conan remote add gitlab https://gitlab.com/api/v4/packages/conan -f
        conan user ta-lu-cien -r gitlab -p ${{ secrets.GITLAB_UPLOAD_PWD }}
        conan install gdal/3.8.3@terranum-conan+gdal/stable -o gdal:with_curl=True -o gdal:shared=True --build=missing
        conan upload wxpdfdocument/1.3.1@terranum-conan+wxpdfdocument/stable --remote=gitlab -q 'build_type=Release' 

