name: mariadb Windows Build
# This workflow will build the mariadb library for Windows using CMake and Conan

#on:
#  release:
#    types: [created]

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python "3.12"
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Conan
      run: |
        python -m pip install --upgrade pip
        pip install wheel conan==1.*

    - name: Install Conan Libraries
      shell: bash
      run: |
        conan remote add gitlab https://gitlab.com/api/v4/packages/conan -f
        conan user ta-lu-cien -r gitlab -p ${{ secrets.GITLAB_UPLOAD_PWD }}
    
    - name: Build mariadb
      shell: bash
      run: |
        pwd
        ls
        cd mariadb-main 
        conan source . --source-folder=_bin/source
        conan install . --install-folder=_bin/build --build=missing
        conan build . --source-folder=_bin/source --build-folder=_bin/build
        conan package . --source-folder=_bin/source --build-folder=_bin/build --package-folder=_bin/package
        conan export-pkg . terranum-conan+mariadb/stable --source-folder=_bin/source --build-folder=_bin/build
        conan test test_package mariadb/10.6.22@terranum-conan+mariadb/stable
        conan upload mariadb/10.6.22@terranum-conan+mariadb/stable --remote=gitlab -q 'build_type=Release' 

