name: wxPdfDocument OSX Build
# This workflow will build the wxWidgets library for OSX using CMake and Conan

#on:
#  release:
#    types: [created]

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python "3.12"
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Conan
      run: |
        python -m pip install --upgrade pip
        pip install wheel conan==1.*

    - name: Install Conan Libraries
      shell: bash
      #working-directory: ${{github.workspace}}/build
      run: |
        conan remote add gitlab https://gitlab.com/api/v4/packages/conan -f
        conan user ta-lu-cien -r gitlab -p ${{ secrets.GITLAB_UPLOAD_PWD }}
        conan install wxpdfdocument/1.3.1@terranum-conan+wxpdfdocument/stable -o wx_version=3.3.1 --build=missing
        conan upload wxpdfdocument/1.3.1@terranum-conan+wxpdfdocument/stable --remote=gitlab -q 'build_type=Release' 

